name: Build static site to gh-pages branch

on:
  push:
    branches: ["main", "master"]

  workflow_run:
    workflows: ["Ingest Agent-to-Agent (A2A) from remote repo via issue", "Ingest Model Context Protocol (MCP) from remote repo via issue"]
    types:
      - completed
  
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
      
      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git config --global credential.helper store
          echo "https://${{ secrets.GITHUB_TOKEN }}@github.com" > ~/.git-credentials
            
      - name: Build and deploy Registry
        run: bash $GITHUB_WORKSPACE/xreg/build_registry.sh 